# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40c79fca01f0aefed852e6b5aeba465c0b0a2c4d15b162ae388652c9d4b60981a862a084935c95b168adede380c90778ec7031e1244250e3a03cffc7d00da7f8

test:
  secret_key_base: c6f47ff699f8d384d03e6f33c772813c270350a2441dbbb24c4b3eabc2c230bb40b4a528028a716c1f569d3d92e63d60cff7f35b554ccfa795f3e30b1353f2d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
